### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by TianyuZhuuu** [ucfnlp/summarization#2]
Dear authors,

Thanks for sharing an interesting and novel work. Congratulates!

After reading the paper, I'm confused about how to get output summary given predicted extractive labels. After obtaining the word/chunk extractive labels during inference stage, we just concatenate words/chunks with label 1 to get the summary or apply some other post processing?

Thanks.

**Comment by kristjanArumae** [comment]
Hi.  Thanks for your interest in our work! 

In model/myio.py line : 266 is the function that gets called for rouge evaluation processing.  While this saves the concatenated text, there is an additional .json file that saves the raw text and the corresponding mask (aligned system labels).  From there you should be able to construct readable output.

**Comment by TianyuZhuuu** [comment]
OK, I will check it out. Thanks for your reply!
